services:
  feedback-mechanism-db:
    image: postgres:15.0
    restart: always
    container_name: feedback-mechanism-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - ./docker/local:/docker-entrypoint-initdb.d
    ports:
      - "5407:5432"
    networks:
      - cpdata-network

networks:
  cpdata-network:
    name: cpdata-network
    driver: bridge
    external: true
